### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by channprj** [pythonkr/blog#2]
- 404 에러페이지 추가
- 안내멘트 + [구글 커스텀 검색엔진](https://cse.google.co.kr/cse/all) 달기

**Comment by tebica** [comment]
GCE 가 뭐지? Google Compute Engine?

**Comment by channprj** [comment]
GCSE 인데 모바일로 적다가 오타를 냈네요. 수정했습니다.

**Comment by syohnet** [comment]
오랫동안 미처리 이슈로 닫습니다.
